# spring.application.name=back-end

# spring.datasource.url=jdbc:mysql://localhost/cms?usessl=false
# spring.datasource.username=root

# spring.datasource.password=26482008
# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.open-in-view=false

# spring.data.mongodb.uri=mongodb://localhost:27017/prescriptions

# management.endpoint.health.show-details=always
# management.health.db.enabled=true


# api.path=/
# jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M



# spring.web.resources.static-locations=classpath:/static/

# # -------------------------
# # Thymeleaf Configuration
# # -------------------------
# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html
# spring.thymeleaf.mode=HTML
# spring.thymeleaf.cache=false    
# spring.thymeleaf.encoding=UTF-8
#-------------------------------------
spring.application.name=back-end

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MySQL connection (updated for Docker)
spring.datasource.url=jdbc:mysql://172.21.105.92:3306/cms
spring.datasource.username=root
spring.datasource.password=z9EvRmQsonnJm7l7dfbNl1TB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# MongoDB connection (updated for Docker)
spring.data.mongodb.uri=mongodb://root:Z4NNrBsAMlSKAE15kUtodyJ9@172.21.117.113:27017/prescriptions?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true

api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M

spring.web.resources.static-locations=classpath:/static/

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8